### ISSUE TITLE
Week 7 ready for grading

### ISSUE THREAD

**Issue by lzingg1-matc** [madisoncollege-it-programs/python-scripting-lzingg1-matc#8] opened 2022-10-16 19:12 UTC
No questions as of now.

**Comment by cethenmc** [comment] 2022-10-18 04:47
Hi, Luke.  # 5 on this assignment was intended to have you add two more records to an already established dictionary (which you established in # 1).  As a result, I will record a 7 of 8, until you send the correction in.  Please reply to this GitHub Issue Ticket to let me know when you have pushed your change to GitHub.  If you just want to take the 7 out of 8, then please reply to this Issue ticket, as well, letting me know.  ~Chris

**Comment by lzingg1-matc** [comment] 2022-10-27 18:01
Changes have been made.

**Comment by cethenmc** [comment] 2022-11-02 16:27
This looks good now.  Closing ticket.

**Closed by cethenmc** 2022-11-02 16:27 UTC
